<a href="https://colab.research.google.com/github/lucianoselimaj/MLDL_Labs/blob/main/Lab01_Ex01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises




In [ ]:
#Tensors Attributes

"""
Shape --> tesnor.shape
Data Type --> tensor.dtype
Device --> tensor.device
"""

#Arithmetic Operations
"""
torch.add(tensorA, tensorB) --> is equivalent to a+b
torch.mul(tensorA,tensorB) --> is equivalent to a*b
"""



### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Directly from data tensor = torch.tensor([[1,2],[3,4]])
# From a numpy array tensor = torch.from_numpy(np_arr)
# From another tensor (preserving only the shape, datatype, etc.) tensor = torch.rand_like(tensor)
# with random or constant values tensor = torch.ones(), torch.rand(), torch.zeros()


# Create random tensor
rand_tensor = torch.rand(7,7)


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
rand_two_tensor = torch.rand_like(rand_tensor.T)
#rand_two_tensor = torch.rand(1,7)

# Perform matrix multiplication
mm = rand_tensor @ rand_two_tensor
mm = torch.mm(rand_tensor, rand_two_tensor)
mm = torch.matmul(rand_tensor, rand_two_tensor)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
rand_one = torch.rand(2,3)
rand_two = torch.rand_like(rand_one.T)


# Matrix multiply tensors
mul = rand_one @ rand_two
mul = torch.mm(rand_one,rand_two)
mul = torch.matmul(rand_one,rand_two)


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
seed = 1234

#CPU
torch.manual_seed(seed)
#GPU
torch.cuda.manual_seed(seed)
# same seed for all GPUs
torch.cuda.manual_seed_all(seed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if(torch.cuda.is_available()):
   device = torch.device("cuda")

# Create two random tensors on GPU
t_cuda_one = torch.rand(4,5, device= device)
t_cuda_two = torch.rand(5,4, device = device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
cuda_mm = torch.matmul(t_cuda_one, t_cuda_two)
cuda_mm = t_cuda_one @ t_cuda_two
cuda_mm = torch.mm(t_cuda_one,t_cuda_two)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = cuda_mm.max()
print(max)
# Find min
min = cuda_mm.min()
print(min)


tensor(1.7299, device='cuda:0')
tensor(0.2386, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(cuda_mm.argmax())

# Find arg min
print(cuda_mm.argmin())


tensor(8, device='cuda:0')
tensor(11, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)


# Create random tensor
t = torch.rand(1,1,1,1,10)


# Remove single dimensions
t_reshaped = t.squeeze()


# Print out tensors and their shapes
print(t, t.shape)
print(t_reshaped, t_reshaped.shape)


tensor([[[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]]) torch.Size([1, 1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
