<a href="https://colab.research.google.com/github/lucianoselimaj/MLDL_Labs/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy: Numerical Python <br>


*   Stores and operates on dense data buffers
*   Efficient storage and operations

Array <br>
It is the main object provided by Numpy:
*   Fixed Type (all elements have the same type)
*   Multidimensional



In [3]:
import numpy as np

#vector
v = np.array([1,2,3])

#multidimensional
m = np.array([[1,2,3],[4,5,6]])

Vector:
*   shape(3,) --> x0 <br>

2D Matrix:
*   shape(2,3) --> x0,x1<br>

3D Array:
*   shape(3,2,3) --> x0,x1,x2









In [ ]:
#creation from a list
l = [[1,2,3][5,6,7]]
a = np.array(l)

z = np.zeros((2,3))
o = np.ones((3,))
f = np.full((2,2),5)

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-2-a6d723d11e30>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  l = [[1,2,3][5,6,7]]


TypeError: list indices must be integers or slices, not tuple

In [ ]:
#generates num samples from star to stop(included)
arr = np.linspace(0,1,11) # generates 11 numbers from 0 to 1

#Generates numbers from start to stop(excluded), with step
arr = np.arange(1,7,2) #output [1,3,5]

#Generates random data with normal distribution
arr = np.random.random((2,3))
#arr = np.random.random(mean,std, shape)

array([[0.98018658, 0.70949758, 0.94251269],
       [0.9963771 , 0.06862072, 0.9720447 ]])

Array attributes

In [ ]:
x = np.array[[1,2,3],[4,5,6]]

#Number of dimensions of the array
x.dim

#shape
x.shape

#size = product of the shape values (tot number of elements --> shape(2,3)= 2*3)
x.size

Computation on Numpy:

Universal functions (element wise):
*   Binary operations (+, -, /, //, **, %, ecc...)
*   Unary operations (np.abs(x), np.exp(x), np.sin(x), ecc...) they apply the op separately to each element of the arrayù
*   Aggregate functions: returns a single value from an array (np.min(x) or x.min(), x.argmin(), x.sum() ecc...)

Using axis in Aggregate functions:
Vector: we have only one axis --> 0 <br>

2D array
*   axis 0 --> indicates rows but works for each column
*   axis 1 --> indicates columns but works by rows

nb: uando passi axis=X, stai dicendo: "Applica la funzione lungo questo asse → quindi ogni volta che collassi l'asse, agisci sugli elementi perpendicolari".






In [5]:
#Aggregate Function
x=np.array([[1,1],[2,2]])
x.sum()

# For a 1D array returns the index, for nD array returns the position of the flatted version
x.argmin()

#Aggregate functions using axis
x.argmax(axis=0)

array([1, 1])

# **Sorting**: <br>
We have two possible solutions:
*   np.sort(x): creates a sorted copy of x
*   x.sort(): sorts x inplace (x is modified)

NB: by default sorts along the last axis (-1)



In [8]:
x = np.array([[2,1,3],[7,9,8]])

#copy of x
x_2 = np.sort(x)
print(x_2)
x_2[[0],[0]] = 100
print()
print(x)


[[1 2 3]
 [7 8 9]]

[[2 1 3]
 [7 9 8]]


If we don't want to sort the array but we want only the index of the sorted array we should use **np.argsort()**

In [10]:
x = np.array([[2,1,3],[7,9,8]])

# by default axis= -1
np.argsort(x)

array([[1, 0, 2],
       [0, 2, 1]])

# Broadcasting:
pattern designed to perform operations between arrays with different shape <br>
Rules of Broadcasting:

*   The shape of the array with fewer dimensions is
padded with leading ones: x.shape = (2, 3), y.shape = (3) --> y.shape = (1, 3)
*   If the shape along a dimension is 1 for one of the arrays
and >1 for the other, the array with shape = 1 in that
dimension is stretched to match the other array: x.shape = (2, 3), y.shape = (1, 3) --> stretch: y.shape = (2, 3)
*  If there is a dimension where both arrays have shape >1
and those shapes differ, then broadcasting cannot be
performed


In [ ]:
x = np.array([1, 2, 3])
y = np.array([[11], [12], [13]])

z = x + y

In [ ]:
#error x.shape = (3, 2) y.shape = (3,)
x = np.array([[1, 2],[3,4],[5,6]])
y = np.array([11, 12, 13])

z = x + y

# Accessing Numpy arrays:

In [ ]:
#SIMPLE INDEXING
x = np.array([[2, 3, 4],[5,6,7]])
x[1, 2] # read value (indexing)

#returning elements from the end:
x[0,-1]

#SLICING x[start:stop:step]:
creates a view of the elements from start(included) to stop(excluded). So if we update the view yield updates on the original array

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[:, 1:] # or x[0:3, 1:3]

# **Masking** <br>
use boolean masks to select elements x[mask]. <br>
Remember that masking does not creates views, but copies

In [13]:
x = np.array([1.2, 4.1, 1.5, 4.5])
print( x > 4)
x[x > 4]

[False  True False  True]


array([4.1, 4.5])

# Fancy indexing
specify the index of elements to
be selected

In [ ]:
#Vector
x = np.array([7.0, 9.0, 6.0, 5.0])
x[[1, 3]] #[9.0, 5.0]

In [ ]:
#2D array
x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0],
[6.0, 7.0, 8.0]])

arr[[0, 2], :]  # Seleziona riga 0 e riga 2
arr[[0, 1], [1, 2]] #seleziona elementi specifici (coordinate)

"""
Quando fai arr[[a, b], [c, d]], stai selezionando:

arr[a, c]

arr[b, d]
"""


# Working with arrays
* Array concatenation
* Array splitting
* Array reshaping
* Adding new dimensions

In [ ]:
#Concatenation
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
np.concatenate((x, y)) # Default axis: 0

h = np.hstack((x, y)) # along rows (horizontal)
v = np.vstack((x, y)) # along columns (vertical)

# Splitting arrays (split, hsplit, vsplit)
np.split(arr, N, axis=0)
* outputs a list of Numpy arrays
* If N is integer: divide arr into N equal arrays (along axis), if
possible!
* if N is a 1d array: specify the entries where the array is
split (along axis)

In [ ]:
x = np.array([7, 7, 9, 9, 8, 8])
np.split(x,[2,4]) # split before element 2 and 4 # same as passing N = 3

# Reshaping

At most one dimension can be -1 (“unknown”). If present, the size is inferred from :
* The source array
* The other dimensions

In [ ]:
x = np.arange(6)
y = x.reshape((2,3))

# Adding new dimensions
**np.newaxis** adds a new dimension with shape=1 at
the specified position

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
res = arr[np.newaxis, :, :] # output shape = (1,2,3)
print(res)